spring.application.name=online-exam

server.port=${PORT:7890}

# ===============================
# MYSQL DATABASE CONFIGURATION
# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/exam_db?createDatabaseIfNotExist=true}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:112}

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}

# ===============================
# FILE UPLOAD
# ===============================

file.upload-dir=${FILE_UPLOAD_DIR:./uploads}
